#!/bin/sh

### BEGIN INIT INFO
# Provides: spigot
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Spigot server control script
### END INIT INFO

#
# Start Spigot server
#
start() {
    echo "Starting Spigot server..."
}

#
# Stop Spigot server
#
stop() {
    echo "Stopping Spigot server..."
}

case "$1" in
    start)
        start
    ;;

    stop)
        stop
    ;;

    restart)
        stop
        start
    ;;
esac

exit 0
